exclude = [
    ".git",
    "__pycache__",
    ".env",
    ".venv",
    "env",
    "venv",
    "ENV",
    "env.bak",
    "venv.bak",
    "ctypes",
    "pydispatch",
]

ignore = [
    "E402",     # module-import-not-at-top-of-file
    "E501",     # line-too-long
    "F821",     # undefined-name
    "ANN201",   # missing-return-type-undocumented-public-function
    "ANN101",   # missing-type-self
    "ANN102",   # missing-type-cls
    "ANN206",   # missing-return-type-class-method
    "ANN001",   # missing-type-function-argument
    "S310",     # suspicious-url-open-usage
    "B909",     # loop-iteration-mutation
    "A002",     # builtin-argument-shadowing
    "EXE001",   # shebang-not-executable
    "PT009",    # pytest-unittest-assertion
    "SLF001",   # private-member-access
    "PLC1901",  # compare-to-empty-string
    "PLR0913",  # too-many-arguments
    "PLR0915",  # too-many-statements
    "PLR0912",  # too-many-branches
    "PLR0914",  # too-many-local-variables
    "PLR0917",  # too-many-positional-arguments
    "PLR1730",  # if-stmt-min-max
    "PLR6201",  # literal-membership
]

[lint.per-file-ignores]
"lib_dop/r_dop_import_lib.py" = ["ERA001", "PLR2004"]
"testsuite/r_dop_import_test_base.py" = ["PLR2004"]
