name: Python Flake8, black and pylint code quality check

on: [push]

jobs:
  lint:
    uses: mundialis/github-workflows/.github/workflows/linting.yml@main
    with:
      VALIDATE_HTML: false
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
    - name: Install apt dependencies
      run: |
        sudo apt-get install -y -qq python3 python3-pip
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install ruff==0.5.7
        ruff --version
    - name: Lint with ruff
      run: |
        ruff check --config pyproject.toml .